[package]
name = "block_boss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bc_hash = { path = "../bc_hash/" }
chrono = "0.4.23"